version: '2'
services:
  php:
    image: php:8-apache
    container_name: meu-php
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - /Users/murilolima/Documents/projects/rotas-e-autenticacao/public:/var/www/html
    links:
      - db
  db:
    image: mysql:latest
    container_name: devmysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root